apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: eckdemo
spec:
  version: 7.6.2
  http:
    service:
      spec:
        type: LoadBalancer
  nodeSets:
    - name: master
      count: 3
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
    - name: data
      count: 10
      config:
        node.master: false
        node.data: true
        node.ingest: true
        node.ml: true
        cluster.remote.connect: false