apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: eckdemo
spec:
  version: 7.6.2
  count: 1
  elasticsearchRef:
    name: eckdemo
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        disabled: true